OSG/OSG/Controllers/MemberPriceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OSG.Controllers
{
    public class MemberPriceController : Controller
    {
        // GET: MemberPrice
        public ActionResult Index()
        {
            return View();
        }
    }
}

OSG/OSG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Old School Gym</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/Masonry.js"></script>
</head>
<body>
    <div id="bg">
        <img src="~/Content/Pictures/bg4.jpg" alt="">
    </div>
    <div id=" fb-root"></div>
    <script>
        (function (d, s, id) {
            var fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            var js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/da_DK/sdk.js#xfbml=1&version=v2.5";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @*@Html.ActionLink("Old School Gym", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="logo">
                        <a href="../Home/Index"><img src="~/Content/Pictures/oldschoolgym logo.png" /></a>
                    </li>
                    <li>@Html.ActionLink("Nyheder", "Index", "News")</li>
                    <li>@Html.ActionLink("Events", "Index", "Events")</li>
                    <li>@Html.ActionLink("Priser", "Index", "MemberPrice")</li>
                    <li>@Html.ActionLink("Om os", "Index", "Trainer")</li>

                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row frontpage_footer">
                <div class="col-md-4 contact">
                    <table>
                        <tr>
                            <td>
                                <h4>Kontakt</h4>
                            </td>
                        </tr>
                        <tr>
                            <td>Telefon : +45 26 98 70 66</td>
                        </tr>
                        <tr>
                            <td>Email : info@oldschoolgymesbjerg.dk</td>
                        </tr>
                        <tr>
                            <td>Eller kom forbi i centret til en snak!</td>
                        </tr>
                        <tr>
                            <td>
                                <div class="fb-like" data-href="https://www.facebook.com/Old-School-Gym-Esbjerg-1670721003141954/" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="col-md-4 openinghours">
                    <table>
                        <tr>
                            <td>
                                <h4>Åbningstider</h4>
                            </td>
                        </tr>
                        <tr>
                            <td>Mandag - Søndag</td>
                            <td>&nbsp;5.00 - 23.00</td>
                        </tr>
                        <tr>
                            <td><h5 class="bemandet">Bemandet åbningstider:</h5></td>
                        </tr>
                        <tr>
                            <td>Mandag - Fredag</td>
                            <td>&nbsp;8.00 - 20.00</td>
                        </tr>
                        <tr>
                            <td>Lørdag - Søndag</td>
                            <td>&nbsp;9.00 - 14.00</td>
                        </tr>
                    </table>
                </div>
                <div class="col-md-4 embedded_map">
                    <table>
                        <tr>
                            <td>
                                <iframe width="340" height="200" frameborder="0" style="border: 0"
                                        src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJt4FCH9UgS0YROI6cgBEhp-0&key=AIzaSyBdyJRYWh1mzBHlLDgqbx0GQ1Zoj9RHR4M" allowfullscreen></iframe>
                            </td>
                        </tr>
                    </table>
                    <div style="clear: both;"></div>
                </div>
            </div>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>